my_snowflake_db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: xskqzat-bk95941
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: ACCOUNTADMIN
      database: DATA2DAY_DEMO
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 2
      client_session_keep_alive: False
      query_tag: dbt
