version: 2

sources:
  - name: PUBLIC
    tables:
      - name: raw_customers
        meta:
          dagster:
            asset_key: ["raw_customers"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_orders
        meta:
          dagster:
            asset_key: ["raw_orders"]
      - name: raw_payments
        meta:
          dagster:
            asset_key: ["raw_payments"]
      - name: source_parquet_data
        meta:
          dagster:
            asset_key: ["source_parquet_data"]
